### ISSUE TITLE
Projections disappear when entering projection volume when "Use Stencil Test" is enabled.

### ISSUE THREAD

**Issue by Nolram12345** [nyahoon-games/ProjectorForLWRP#2]
See title.

**Comment by takaokato** [comment]
Thank you for reporting the issue. Do you mean a projection of a projector disappear when entering projection volume of other projectors? I couldn't reproduce this issue by modifying the sample scene. Can you reproduce it in the sample scene?

By the way, I noticed another issue that happens when Stencil Mask in Projector Renderer Feature does not have bit-0. I fixed it in the commit 25f7cf1f537d6e1f187287ac2990cae85d46a55e. I don't think that fixes your issue, but please give this commit a try.

**Comment by Nolram12345** [comment]
No, I do not mean projection volume from another projector - I mean the exact same projector. This also only happens when "Use Stencil" test is enabled. Here is a GIF :
![SNtkneqj3s-min](https://user-images.githubusercontent.com/37701550/112505235-e1503500-8d8c-11eb-9d7f-e290f5726557.gif)

**Comment by Nolram12345** [comment]
Note : The same happens with the example shadow.

**Comment by Nolram12345** [comment]
Tried the latest version, same issue still appears. Any fix for this ?

**Comment by takaokato** [comment]
Thank you for the video. I understand. You meant "when the main camera enters the projection volume". I forgot to consider this case. Fixed in commit 2942846ce4429af360e59b5162623fd83e1734c0.

**Comment by Nolram12345** [comment]
Great !

**Comment by Nolram12345** [comment]
New issue : Use Stencil Test no longer respects transparent objects. This causes issues like this : 
![grafik](https://user-images.githubusercontent.com/37701550/112998843-b68c2500-916e-11eb-9e9c-ef9615d319b9.png)

**Comment by takaokato** [comment]
Do you use stencil test for the transparent objects? Stencil Buffer is no longer cleared by default. It will affect other rendering which uses stencil test. Please check `Clear stencil after draw` or, remove the stencil bits that are used for other rendering from `Stencil Mask` property of `Render Projector Feature`. See Readme for more details.

**Comment by Nolram12345** [comment]
Well, I haven't really done anything with it. "Use Stencil test" used to remove those unwatned shadows on the objects transparent parts, but it no longer does. I don't really know what to set the Stencil Mask to - the Editor hangs when I set it to 255 or more.

**Comment by takaokato** [comment]
I'm sorry, I guess you set Stencil Mask to 256, that caused infinite loop. I fixed it in commit e14ac0fb0c491e148119053c40f3dfb3131df91e.

If you don't know which stencil bits are used for the transparent objects, just try to check `Clear stencil after draw` in the projector.

**Comment by Nolram12345** [comment]
I have tried with Clear stencil, but it doesn't appear to have done anything.
![grafik](https://user-images.githubusercontent.com/37701550/113123662-0f15fd80-9215-11eb-9f95-98333dae6b4e.png)

**Comment by takaokato** [comment]
Is the issue really related to stencil test? Which shader do you use for the transparent object?

**Comment by Nolram12345** [comment]
I am using the standard lit shader. 
![grafik](https://user-images.githubusercontent.com/37701550/113134809-949faa80-9221-11eb-901c-ce9f121d7b7d.png)

**Comment by takaokato** [comment]
I think stencil test has nothing to do with the issue. Basically, projector does not support projecting a texture onto a surface that uses Alpha Clipping. This is because projector shader cannot use the main texture of the transparent object. However, if you write a special projector shader which uses a texture for alpha clipping, and set the texture property to the leaf texture, you can use the projector for the transparent object.

**Comment by Nolram12345** [comment]
Hmm, and how would I got about writing such a shader ? And why did it work before the last patch ?

**Comment by takaokato** [comment]
Before fixing this issue, stencil buffer was cleared during projection rendering, which could avoid drawing projection multiple times on the same surface. However, this was a side effect of stencil test (and was not good for performance). Stencil test is provided only for improving the performance, and it is not recommended to use stencil test for solving other issues.
For writing projector shaders, please read Readme and Unity Manual (https://docs.unity3d.com/Manual/SL-ShaderPrograms.html).

**Comment by Nolram12345** [comment]
Hmm, but then wouldn't it be possible to "unfix" the issue and make it a seperate option ?

**Comment by takaokato** [comment]
Okay, I will add an option for avoiding multiple projection, instead of undoing the fix. Please wait for my next commit.

**Comment by Nolram12345** [comment]
Sure, thank you very much !

**Comment by takaokato** [comment]
No problem. I already committed. Check `Prevent overwriting` and uncheck `Clear stencil` has almost same behaviour as before, but it supports the case that the camera enters the projection volume. If it works as you expected, I would like to close this issue.

**Comment by Nolram12345** [comment]
Yes, everything is satisfactory now ! Thank you !

**Comment by takaokato** [comment]
You're welcome. Thank you for the bug report and feedback.
